version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: test-aws
    command: gunicorn practice.wsgi:application --bind 0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles/
    
    depends_on:
      -  backend_postgres
  backend_postgres:
    image: postgres:11.18-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: mydatabaseuser
      POSTGRES_DB: mydatabase
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  


