# Generated by Django 4.0.5 on 2022-09-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'A time pass model', 'verbose_name_plural': 'Dummy-Model'},
        ),
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('largecount', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.PROTECT, related_name='test2', to='dummy.test')),
            ],
            options={
                'verbose_name': 'Test2',
                'verbose_name_plural': 'Test2s',
            },
        ),
    ]
